import '../styles/globals.css';

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children, params }) {
  const locale = params?.locale || 'uk';

  return (
    <html lang={locale}>
      <body>
        <div>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}