import '../styles/globals.css';
import { AuthProvider } from '@/context/AuthContext';

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {

  return (
    <html>
      <body>
      <AuthProvider>
        {children}
      </AuthProvider>
      </body>
    </html>
  );
}